[package]
name = "rust-crash-course"
version = "0.1.0"
edition = "2021"

[features]
default = ["exercises", "solutions"]
exercises = []
solutions = []

[dependencies]
cfg-if = "1.0.0"
tokio = {version = "1.44", features=["full"]}
